-- Exploratoty data analysis
# Dimension Exploration, wich means identfying unique values or categories in each dimenssion
# Recognizing how data might be grouped or segmented, which is useful for later analysis.

-- Explore All Cities customers come from
SELECT DISTINCT City FROM walmart;

-- Explore All Categories
SELECT
 DISTINCT Category, Product_Name 
FROM walmart
ORDER BY Category, Product_Name;

-- Date Exploration
# Identfy the earliest and latest dates "Boundaries"
# Understand the scop of data and the timespan

-- Find the fist & last purchase date
-- How many months of sales are avilable
SELECT
 MIN(Purchase_Date) AS first_purchas,
 MAX(Purchase_Date) AS last_purchas,
 timestampdiff(month, MIN(Purchase_Date), MAX(Purchase_Date)) As purchase_range_months
FROM walmart;

-- Find the youngest and oldest customer
SELECT
 MIN(age) AS youngest,
 MAX(Age) AS oldest
FROM walmart;


# Measures Exploration
-- Find total sales
SELECT 
	SUM(Purchase_Amount) AS total_sales
FROM walmart;

-- Find how many items are sold
SELECT 
	COUNT(*) AS total_orders
FROM walmart;

-- Find the total number of products
SELECT 
	COUNT( DISTINCT Product_Name) total_products
FROM walmart;

-- Find the total number of customers
SELECT 
	COUNT(DISTINCT Customer_ID) total_customers
FROM walmart;

-- Find All payment method
SELECT 
	COUNT(DISTINCT Payment_Method) AS number_payment
FROM walmart;

-- Find the lowest and highst Rating scores
SELECT 
	MIN(Rating) AS lowest_rating,
    MAX(Rating) AS highest_rating
FROM walmart;

-- Generate a report that shows all key metrics of the business
SELECT 
'Total Sales' AS Measure_name,	
SUM(Purchase_Amount) AS Measure_value
FROM walmart
UNION ALL
SELECT 
'Total Order', COUNT(*)
FROM walmart
UNION ALL
SELECT 
'Total Products', COUNT( DISTINCT Product_Name) 
FROM walmart
UNION ALL
SELECT 
'Total Customers',	COUNT(DISTINCT Customer_ID) 
FROM walmart
UNION ALL
SELECT 
'Number of payemnt', COUNT(DISTINCT Payment_Method) AS number_payment
FROM walmart;


# Magnitude
# Compare the Measure value by category
# it helps us understand importance of different categories

-- Find total customer by city;
SELECT 
City, 
COUNT(Customer_ID) AS total_customer
FROM walmart
GROUP BY City
ORDER BY total_customer DESC;

-- Find total customer by gender;
SELECT 
Gender, 
COUNT(Customer_ID) AS total_customers
FROM walmart
GROUP BY Gender
ORDER BY total_customers DESC;

-- Find total product by category
SELECT 
Category, 
COUNT(Product_Name)  AS total_products
FROM walmart
GROUP BY Category
ORDER BY total_products DESC;

-- What is the avg sales in each category
SELECT 
Category, 
round(AVG(Purchase_Amount),2)  AS avg_sales
FROM walmart
GROUP BY Category
ORDER BY avg_sales DESC;

-- What is the total revenue generated for each category
SELECT 
Category, 
SUM(Purchase_Amount)  AS total_sales
FROM walmart
GROUP BY Category
ORDER BY total_sales DESC;

-- Find total revenue is generated by each customer
SELECT 
Customer_ID, 
SUM(Purchase_Amount)  AS total_sales
FROM walmart
GROUP BY Customer_ID
ORDER BY total_sales DESC;                   

SELECT * FROM walmart;
-- What is the distribution of sold items across cities
SELECT 
City, 
COUNT( Product_Name)  AS avg_sales
FROM walmart
GROUP BY City
ORDER BY avg_sales DESC;

-- What is the highest rating product

SELECT 
	Product_Name,
    MAX(Rating) AS max_rating
FROM walmart
GROUP BY Product_Name;

# Ranking
-- Wich 5 products generate the highest revenue and rated as 5
SELECT *
FROM (
SELECT 
	Product_Name,
    SUM(Purchase_Amount) AS highest_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(Purchase_Amount) DESC) AS rank_products
FROM walmart
GROUP BY Product_Name) t
WHERE rank_products <= 5;

-- Any product that rated under 2 flag  as worest 
SELECT * FROM(
SELECT 
	Product_Name,
    Rating,
    SUM(Purchase_Amount) AS worest
FROM walmart
GROUP BY Product_Name, Rating) t
WHERE Rating < 2;

-- Find the customers who generated more than 400

WITH highe_sales AS
(
SELECT
Customer_ID,
SUM(Purchase_Amount) AS total_sales
FROM walmart
GROUP BY Customer_ID
ORDER BY total_sales DESC)
SELECT * FROM highe_sales
LIMIT 10;

-- Find the change over time sales "trndes" 
SELECT
 year(Purchase_Date) AS order_year,
 month(Purchase_Date) AS order_month,
 SUM(Purchase_Amount)  AS total_sales,
 COUNT(DISTINCT Customer_ID) AS total_custmers
FROM walmart
GROUP BY year(Purchase_Date),  month(Purchase_Date)
ORDER BY year(Purchase_Date),  month(Purchase_Date);

-- Claculate total sales per mont
-- and the runinng total over time
SELECT
order_date,
total_sales,
SUM(total_sales) OVER(PARTITION BY order_date ORDER BY order_date) AS running_total,
AVG(sales_avg) OVER(ORDER BY order_date) AS moving_avg
FROM(
SELECT
 month(Purchase_Date) AS order_date, 
 SUM(Purchase_Amount) AS total_sales,
 AVG(Purchase_Amount) AS sales_avg
FROM walmart
GROUP BY month(Purchase_Date))t;

-- Anayze the yearly preformance of products by comparing their sales
WITH yearly_product_sales AS
(
SELECT 
year(Purchase_Date) AS year_order,
Product_Name,
SUM(Purchase_Amount) AS current_sales
FROM walmart
GROUP BY year(Purchase_Date), Product_Name)
SELECT 
year_order,
Product_Name,
current_sales,
ROUND(AVG(current_sales) OVER(PARTITION BY Product_Name),0) AS product_avg,
current_sales - ROUND(AVG(current_sales) OVER(PARTITION BY Product_Name),0) AS diff_avg
FROM yearly_product_sales
GROUP BY Product_Name, year_order;